### ISSUE TITLE
Orphaned file links in the gemspec

### ISSUE THREAD

**Issue by nashbridges** [semaperepelitsa/subdomain_locale#4] opened 2014-01-04 17:06 UTC
```
subdomain_locale at ... did not have a valid gemspec.
This prevents bundler from installing bins or native extensions, but that may not affect its functionality.
The validation message from Rubygems was:
  ["test/controller_test.rb", "test/lib/i18n.rb", "test/acceptance_test.rb"] are not files
```

Maybe `git ls-files` is less error-prone.

**Comment by semaperepelitsa** [comment] 2015-06-01 18:03
Sorry, I forgot to comment on this. Before making a release I always update Manifest using `git ls-files` and check to see if there are any mistakes. So this error should never happen when using releases from Rubygems. I'm closing this since the issue is very old.

**Closed by semaperepelitsa** 2015-06-01 18:03 UTC
